### PR TITLE
Main 2

### PR DESCRIPTION
**Pull request by AlexeyTiunov**
`Task 2.1 Manual deployment`
   What was done:
   1) An  s3 bucket was created through aws console.  http://comersialshopta.s3-website-eu-west-1.amazonaws.com
2) The built project was uploaded to the bucket.
3) The public access was unblocked for the bucket.
4) A permission was added to the bucket.  {
   "Version": "2012-10-17",
   "Statement": [
   {
   "Sid": "GetObjects",
   "Effect": "Allow",
   "Principal": "*",
   "Action": "s3:GetObject",
   "Resource": "arn:aws:s3:::comersialshopta/*"
   }
   ]
   }
4) A static website hosting was turned on for the bucket to have access to.

  `Task 2.2 Automated Deployment` What was done:
   1) Using serverless-finch plugin  a new bucket has been created and the project built was uploaded to the bucket
     with the command "sls client deploy --no-config-change --no-policy-change --no-cors-change".
     Before it the new bucket name was added to the servless.yml (bucketName: comersialshopta2)
     As we just use the only serverless-finch plugin command  the bucket was just created without any other adjustments.
2)  To fully complete the task 2.2 the [serverless-single-page-app-plugin.js](.serverless_plugins%2Fserverless-single-page-app-plugin.js)along with the serverless-finch were used along with other adjustments from yml file:
    a) "sls deploy" - to use serverlees framework to start creating new resources (through CloudFormation) like S3 and CloudFront.
    b)  "sls client deploy --no-config-change --no-policy-change --no-cors-change"  - to update the changes made in the project.
    c) "sls invalidateCloudFrontCache" - invalidate cache to update changes at the CloudFront. 
3)  As API does not work at AWS yet, and thus it is not possible to get product available some notice has been added to the main page. Like " Sorry API is still being developed."
4) To update changes now it is enough to call  "sls client deploy" and "sls invalidateCloudFrontCache".
   https://d359ghg4pp7ul2.cloudfront.net/ - the link for the CloudFront.

### CODE REVIEW

**Review by ezhukauskas — COMMENTED** [review]
Could you add URL to S3-website bucket created with serverless? The URL should return 403

**Comment by ezhukauskas** [comment]
Also please provide CloudFront distribution URL of manually created S3 (task 2.1)

**Comment by ezhukauskas** [comment]
Another point is that manually created S3 bucket is still available on http://comersialshopta.s3-website-eu-west-1.amazonaws.com. Please take a look at [criteria](https://github.com/EPAM-JS-Competency-center/cloud-development-course-initial/blob/main/2_serving_spa/task.md#evaluation-criteria-70-points-for-covering-all-criteria).

This is not a stopper because it was not mentioned in task description (a point to program feedback :)), but anyway take a look [here](https://aws.amazon.com/premiumsupport/knowledge-center/cloudfront-access-to-amazon-s3/), could be useful

**Comment by AlexeyTiunov** [comment]
https://drxdg7s7jy0ez.cloudfront.net - cloudFront

http://comersialshopta.s3-website-eu-west-1.amazonaws.com/ -  s3bucket (with 403 error access)

**Review by ezhukauskas — APPROVED** [review]

**Pull request merged**
